# Generated by Django 5.0.7 on 2024-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                ("foot_note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
